### PR TITLE
Adds Import definitions directory to metadata and apply changes to `Inlezen CROHO.R`

### PR DESCRIPTION
**Pull request by Tomeriko96**
A import_definition directory has been created in `metadata`. A system variable has been created as well to keep the script clean.

In addition, the metadata files have been updated due to the new CROHO data.

- Slightly more NA in 4 columns.
- The assertion file was updated as subsets have become larger with the new CROHO export.

Furthermore, it appears column names had not been imported correctly using LaF. Therefore, a line was added to force the column names to be that of the import definitions.

Lastly, LaF seems to have a preference to have empty rows instead of `NA`. This has been rectified as well.

### CODE REVIEW

**Comment by CorneeldH** [comment]
Hi Tomer,

Changes are good! I read somewhere you were updating / making a new function for reading the 'assertions' and 'import definitions', but I don't see that one yet?

--

This is quite dumb of me, but I hadn't realised these changes were already on this repo (I thought last time I was looking at the OPLAS repo). 

Currently I have here the year 2022 also as config setting and the old CROHO csv in the raw data folder. 

Can you try to update with the newest Inschrijvingen 1CHO with the package of Bram? And can you have a look at the the 1CHO Instroom cohorten for 2023? Then we can update this repo to 2023 :-) We can also look at this together.

**Comment by Tomeriko96** [comment]
Indeed, this was a "sequential" mistake on my part in planning work. I have written a function after making this pull request...

**Comment by Tomeriko96** [comment]
I have commited two changes:

- update renv to have the latest dev version of vusa, to include `read_import_definitions()`
- update the script to use the mentioned function

**Comment by CorneeldH** [comment]
Alleen maar iets in deze thread 👎

**Pull request merged**
